### PR TITLE
Add CarpinchoBot ROS bag

### PR DESCRIPTION
**Pull request by nahueespinosa**
### Proposed changes

Related to #165. Depends on #211.

Adds a ROS bag containing a run with CarpinchoBot from June 8, 2023.

https://github.com/Ekumen-OS/beluga/assets/33042669/06019dff-c372-41cb-a651-45076537d92d

#### Type of change

- [ ] 🐛 Bugfix (change which fixes an issue)
- [x] 🚀 Feature (change which adds functionality)
- [ ] 📚 Documentation (change which fixes or extends documentation)

### Checklist

- [x] Lint and unit tests (if any) pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] All commits have been signed for [DCO](https://developercertificate.org/)

### CODE REVIEW

**Comment by nahueespinosa** [comment]
@francocipollone @serraramiro1 FYI!

**Review by francocipollone — COMMENTED** [review]
Awesome! :rocket:

**Comment by nahueespinosa** [comment]
Closing this as the branch is no longer needed, the bring-up process has been documented and we will most likely upload the bags in a separate repository.

**Comment by glpuga** [comment]
> Closing this as the branch is no longer needed, the bring-up process has been documented and we will most likely upload the bags in a separate repository.

A video from this bagfile, that has actual odometry, would look great in this repo's landing page. The one above can work, but one with the visible laser scans would be even better.

**Pull request closed without merging**
