### PR TITLE
Add NDT benchmark report. Adjust default parameter values for the NDT sensor model.

### PR DESCRIPTION
**Pull request by serraramiro1**
### Proposed changes

Adds a new benchmark report for the `NDT` sensor model for magazino datasets.
Matches NDT sensor model default parameters in the example launch files to match the ones that got empirically tested.
Related to #316.
#### Type of change

- [ ] 🐛 Bugfix (change which fixes an issue)
- [ ] 🚀 Feature (change which adds functionality)
- [x] 📚 Documentation (change which fixes or extends documentation)

### Checklist

_Put an `x` in the boxes that apply. This is simply a reminder of what we will require before merging your code._

- [x] Lint and unit tests (if any) pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] All commits have been signed for [DCO](https://developercertificate.org/)

### CODE REVIEW

**Comment by serraramiro1** [comment]
@hidmic I'd love your thoughts on how to best present this benchmark given that it doesn't follow the current one's format (we can't re-generate it from this repo alone).

**Comment by hidmic** [comment]
We were talking precisely about this with @glpuga and @nahueespinosa earlier today. A report pulled out of nowhere is not ideal. Having old reports in our repository is not either. We need the benchmarking code out, that's on me. Until then, we should probably keep this elsewhere. Thoughts?

**Comment by nahueespinosa** [comment]
Yeah, adding a pdf to this repo might not be the best. I think it makes more sense to move in the opposite direction until we can open source our benchmarking code. We were talking about removing the `beluga_benchmark` package even.

I'd keep the default parameter changes though.

**Comment by serraramiro1** [comment]
Will create a new one so we keep this closed PR as-is for post-facto analysis.

**Pull request closed without merging**
